# 9章補足

In [ ]:
# データ定義
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
print(x)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
[[1 2 3]
 [4 5 6]]


In [ ]:
# 3通りのsum関数

y = x.sum(axis=0)
print(y)

z = x.sum(axis=1)
print(z)

w = x.sum()
print(w)

[5 7 9]
[ 6 15]
21
