## 11.3 重み行列の初期化

### ライブラリのインポート

In [ ]:
# ライブラリのインポート
import torch
import torch.nn as nn

### PyTorchデフォルトでの初期化

In [ ]:
# PyTorchデフォルトでの初期化

# 乱数初期化
torch.manual_seed(123)

# 入力3次元 → 出力2次元の全結合層
# デフォルトではKaiming Uniform（He Uniform)となる
layer = nn.Linear(3, 2)

# 結果確認
print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[-0.2354,  0.0191, -0.2867],
        [ 0.2177, -0.4919,  0.4232]], requires_grad=True)
Parameter containing:
tensor([-0.4196, -0.4590], requires_grad=True)


### PyTorchで重み行列初期化を手動変更

In [ ]:
# PyTorchで重み行列初期化を手動変更

# 初期化用ライブラリのインポート
import torch.nn.init as init

torch.manual_seed(123)
layer = nn.Linear(3, 2)

# weightをXavier一様分布
init.xavier_uniform_(layer.weight)

# biasをすべてゼロ
init.zeros_(layer.bias)

# 結果確認
print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[-0.6922,  0.4961, -0.4048],
        [ 0.4099, -0.9297, -0.6646]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


### バージョン確認

In [1]:
!pip install watermark -qq
%load_ext watermark
%watermark --iversions

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 30.3 MB/s eta 0:00:00

